### ISSUE TITLE
WeakHashMap is not thread safe in FieldName.java 

### ISSUE THREAD

**Issue by fatu** [jpmml/jpmml-model#1]
Hi, I found WeakHashMap is not thread safe in FieldName.java, I suggest that replace it by ConcurrentHashMap.

**Comment by vruusmann** [comment]
Currently, class `FieldName` does not specify a "contract" that would limit the number of `FieldName` instances per String value to exactly one. It is perfectly acceptable if different threads see and operate with different `FieldName` instances.

The current implementation is optimized for "read" performance. If class `WeakHashMap` were replaced with class `ConcurrentHashMap`, then simple look-up operations would be unnecessarily penalized. The main problem, however, is that class `ConcurrentHashMap` would prevent unused `FieldName` instances from being garbage-collected.

Your multi-threaded application should be just fine if you treat `FieldName` instances as regular objects, not as enum constants. For example, you should perform equality checks using the `Object#equals(Object)` method, not the equality operator `==`:

```
FieldName left = ...
FieldName right = ...

// Safe equality check
if((left).equals(right)){
}

// Unsafe equality check
if(left == right){
}
```
