### ISSUE TITLE
Broken build.

### ISSUE THREAD

**Issue by Goorman** [jpmml/jpmml-model#15]
Trying to build this project raises errors related to ErrorListener import
```A required class was missing while executing org.jvnet.jaxb2.maven2:maven-jaxb22-plugin:0.13.1:generate: com/sun/xml/bind/api/ErrorListener```

Full logs of failed build with -X flag included.

[logs.txt](https://github.com/jpmml/jpmml-model/files/1454468/logs.txt)

**Comment by vruusmann** [comment]
Fixed in `1.4-SNAPSHOT` development series.
