### ISSUE TITLE
Ensure Java 9 compatibility

### ISSUE THREAD

**Issue by vruusmann** [jpmml/jpmml-model#17]
Related issues: #15, jpmml/jpmml-lightgbm#7, jpmml/sklearn2pmml#80, openscoring/openscoring#5, and many many others

**Comment by damienrj** [comment]
Okay, looks like it is more complicated than the PR I submitted.  https://github.com/jpmml/sklearn2pmml/pull/92 Does work locally.

**Comment by vruusmann** [comment]
Fixed in `1.4-SNAPSHOT` development series. Also, the JPMML-Model library version 1.4.1 has been propagated to all JPMML model conversion libraries by now.
