### ISSUE TITLE
Refactor Apache Maven plugin to support JSON output data format

### ISSUE THREAD

**Issue by vruusmann** [jpmml/jpmml-model#18]
From the mailbox:

> You are converting pmml models to Java SER data format in a Maven Plugin. Do you have a solution which uses Gradle instead of Maven or is it even possible to do the conversion in Gradle? Nowadays everyone uses Gradle instead of Maven in Android apps so I guess every Android developer have this problem.

**Comment by vruusmann** [comment]
The business logic of a Maven/SBT plugin:

1. Unmarshall PMML file into a `org.dmg.pmml.PMML` class model object (using `org.jpmml.model.JAXBUtil`).
2. Transform the class model object by applying appropriate Visitor API workers on it. For example, saving memory by throwing away SAX Locator information, and interning repeated elements.
3. Serialize the transformed class model object to a SER file (using `org.jpmml.model.SerializationUtil`).

**Comment by minhduc0711** [comment]
@vruusmann Can you explain more on how to do this with Gradle?

**Comment by vruusmann** [comment]
@minhduc0711 Write your own Gradle plugin, similar to my Apache Maven plugin.

This issue is a bit outdated. Today, and going forward, I have zero interest in supporting third party build tools.
