### ISSUE TITLE
Extension mechanism for jpmml-model

### ISSUE THREAD

**Issue by chr1st1anh** [jpmml/jpmml-model#2]
When I try to unmarshal a xml to a jpmml model it wont contain the data specified in the extensions tag. As far as I can tell there is no way to access this or extend the JAXB models without rewriting an important portion of it. 

```xml
  <Extension>
    <Extension1>
<MyExample>
<MiningData>abcd</MiningData>
</MyExample>
    </Extension1>
    <Extension2>
<MyExample>
<MiningData>abcd</MiningData>
</MyExample>
    </Extension2>
 </Extension>
```

The result of this extension would be:
```
[Extension1: null]
[Extension2: null]
```
How could the PMML extension mechanism be used to read the content of extensions without rewriting the parsing mechanism, but rather by extending jpmml?

**Comment by vruusmann** [comment]
The stock version of JPMML-Model makes the contents of the top-level `Extension` element accessible as standard W3C DOM classes. You should try something like this:
```
public void printExtensionContent(Extension extension){
  List<?> content = extension.getContent();
  for(Object object : content){
    // Your Extension1 and Extension2 elements correspond to W3C DOM Node elements
    if(object instanceof org.w3c.dom.Node){
      org.w3c.dom.Node node = (org.w3c.dom.Node)object;
      System.out.println(node.getLocalName());
    }
  }
}
```

If you have a Java class model for `Extension1`, `Extension2` elements, then you can make the JAXB runtime aware about it like this:
```
// The "root resource" of a XJC generated class model is class com.mycompany.mypackage.ObjectFactory
JAXBContext context = JAXBContext.newInstance(org.dmg.pmml.ObjectFactory, com.mycompany.mypackage.ObjectFactory);
Unmarshaller unmarshaller = context.createUnmarshaller();
PMML pmml = (PMML)unmarshaller.unmarshal(...);
```

If you replace the default JAXB context (available via `JAXBUtil#getContext()`) with your own JAXB context as shown above, then the content of the top-level `Extension` element will be mapped from W3C DOM classes to your Java class model classes.

So, technically, the JPMML-Model project is already capable of doing everything you need. It's simply not documented. I added a note to my TODO list that I should expand the concept into a full-blown technical article at Openscoring's blog.

**Comment by chr1st1anh** [comment]
That was exactly what I was looking for.

**Comment by vruusmann** [comment]
Reopening this issue, because the unmarshalling functionality does not work as advertised.

**Comment by vruusmann** [comment]
A blog post about "enriching" PMML documents with custom XML content: http://openscoring.io/blog/2015/05/15/jpmml_model_api_vendor_extensions/
