### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [jpmml/jpmml-model#20]
Hi
The following lines have cryptographic API misuses. <br> File name => pmml-model-example/src/main/java/org/jpmml/model/ObfuscationExample.java: Line number => 30: API name => MessageDigest:Operation on object of type java.security.MessageDigest object not completed. Expected call to digest, update<BR>

**Comment by vruusmann** [comment]
Stupid bots that open fake issues get blocked.
