### ISSUE TITLE
EmbeddedModel Not support

### ISSUE THREAD

**Issue by qinjie545** [jpmml/jpmml-model#24]
Whether  EmbeddedModel supported  or Not ?

What i got when debug my program  below:

```java
@Override
public VisitorAction visit(Regression regression){
	-> throw new UnsupportedOperationException();
}
```

**Comment by vruusmann** [comment]
`DecisionTree` and `Regression` model elements have been deprecated by DMG.org: http://dmg.org/pmml/v4-3/MultipleModels.html (scroll down to "Model Composition")

There's no point in implementing stuff that has not been, and will not be, in practical use.

The point of throwing an exception is to fail fast in case there's an accidental `DecisionTree` or `Regression` model somewhere (perhaps `RegressionModel` mistyped as `Regression`).

**Comment by qinjie545** [comment]
Now I got my way by "Segmentation" + "modelChain",  (TreeMode + RegressionMode)

You really helped me a great favor!      :)

Think for your help very much.   

Good wishes to you!
