### ISSUE TITLE
Stop using ThreadLocal#withInitial(Supplier)

### ISSUE THREAD

**Issue by vruusmann** [jpmml/jpmml-model#27]
See https://github.com/jpmml/jpmml-transpiler/issues/7#issuecomment-743063089

**Comment by atlantis0** [comment]
Hi @vruusmann 

I was attempting to generate a jar library file from pmml (using jpmml-transpiler) and use it inside an Android project. 

How Jar was generated
1. Generate executable jar by cloning this repo (https://github.com/jpmml/jpmml-transpiler) and running `mvn clean install`

Project was compiled with java 8 as follows
mvn -Dmaven.compiler.fork=true -Dmaven.compiler.executable=/Library/Java/JavaVirtualMachines/jdk1.8.0_271.jdk/Contents/Home/bin/javac clean install

2. Run exeucable to generate jar from pmml file
/Library/Java/JavaVirtualMachines/jdk1.8.0_271.jdk/Contents/Home/bin/java -jar jpmml-transpiler-executable-1.1-SNAPSHOT.jar --class-name com.custom.model.sdk.BetterPMML --pmml-input v16.pmml --jar-output v016.jar

Android 

**SDK Version**
minSdkVersion 21 (Lollipop - Android 5)
targetSdkVersion 29 (Android 10)

**Gradle config & dependency** 

compileOptions {
    sourceCompatibility = '1.8'
    targetCompatibility = '1.8'
}

implementation 'org.jpmml:pmml-evaluator:1.5.7'
implementation 'org.jpmml:pmml-evaluator-extension:1.5.7'

**Compile-time issue**
None

**Run-time issue**
Crash with the following stack trace

`E  FATAL EXCEPTION: main
E  java.lang.NoSuchMethodError: No static method withInitial(Ljava/util/function/Supplier;)Ljava/lang/ThreadLocal; in class Ljava/lang/ThreadL
    ocal; or its super classes (declaration of 'java.lang.ThreadLocal' appears in /system/framework/core-oj.jar)
E      at org.dmg.pmml.FieldName.<clinit>(FieldName.java:110)
E      at org.dmg.pmml.FieldName.create(FieldName.java:85)
E      at org.jpmml.evaluator.ResourceUtil.lambda$readFieldNames$0(ResourceUtil.java:42)
E      at org.jpmml.evaluator.-$$Lambda$ResourceUtil$5BT3K3VdeFs3OZwc-3Aiya7HVfk.apply(lambda)
E      at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:194)
E      at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
E      at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
E      at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
E      at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
E      at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:261)
E      at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:439)
E      at org.jpmml.evaluator.ResourceUtil.readFieldNames(ResourceUtil.java:43)
E      at com.custom.model.sdk.BetterPMML.<clinit>(BetterPMML.java:52)`

**Note**
The project compiles and runs successfully on API level 26 and above

It seems that ThreadLocal.withinitial was introduced on Android API 26 and its causing the crash on lower API levels. I tested on a device with API level 24 (Android 7.0)

**Comment by vruusmann** [comment]
Great to see an actionable stack trace!

The culprit is the `org.dmg.pmml.FieldName#CACHE_PROVIDER` thread local field (didn't remember its existence; was thinking about the `org.dmg.pmml.adapters.NodeAdapter#NODE_TRANSFORMER_PROVIDER` thread local field).

**Comment by atlantis0** [comment]
Great. What's the next step? Will there by any replacement for the culprit?

**Comment by vruusmann** [comment]
During the initialization of your application, please set the default value for `org.dmg.pmml.FieldName#CACHE_PROVIDER` manually (and keep it there throughout the lifecycle of the application).

It should be the case that when `ThreadLocal#get()` returns a custom value, then `ThreadLocal#initialValue(..)` is not invoked at all.

Something like this:
```java
class MyApplication {
  // THIS
  static {
    FieldName.CACHE_PROVIDER.set(FieldName.CACHE);
  }

  public void run(){
    PMML pmml = new com.custom.model.sdk.BetterPMML();
  }
}

**Comment by atlantis0** [comment]
This is still causing a crash because `FieldName.CACHE_PROVIDER` will cause `ThreadLocal#withInitial(Supplier)` to be invoked.

**Comment by vruusmann** [comment]
> This is still causing a crash because FieldName.CACHE_PROVIDER will cause ThreadLocal#withInitial(Supplier) to be invoked.

Yes, unfortunately, it's one big chained execution there.

**Comment by atlantis0** [comment]
Got it. Any thoughts on how we can work this out? Maybe prepare a new release without `ThreadLocal#withInitial(Supplier)`

**Comment by vruusmann** [comment]
@atlantis0 I've prepared and published JPMML-Model version 1.5.8 (should become visible in the Maven Central repository in a couple of hours time).

You might try swapping 1.5.7 for 1.5.8 in your Android app classpath to get moving quickly.

**Comment by atlantis0** [comment]
Thank you. But 1.5.8 is causing another issue. See my stack trace

`                         E  Process: com.custom.model, PID: 20018
                         E  java.lang.NoSuchMethodError: No virtual method getParameters()[Ljava/lang/reflect/Parameter; in class Ljava/lang/reflect/Constructor; or its super classes (declaration o
                            f 'java.lang.reflect.Constructor' appears in /system/framework/core-oj.jar)
                         E      at org.jpmml.evaluator.ModelManagerFactory.findConstructor(ModelManagerFactory.java:251)
                         E      at org.jpmml.evaluator.ModelManagerFactory.newModelManager(ModelManagerFactory.java:97)
                         E      at org.jpmml.evaluator.ModelEvaluatorFactory.newModelEvaluator(ModelEvaluatorFactory.java:38)
                         E      at org.jpmml.evaluator.ModelEvaluatorBuilder.build(ModelEvaluatorBuilder.java:115)
                         E      at com.custom.model.sdk.PMMLBuilder.build(PMMLBuilder.java:32)`

**Comment by vruusmann** [comment]
@atlantis0 That's a completely new issue now (affects the JPMML-Evaluator library), see https://github.com/jpmml/jpmml-evaluator/issues/210

Let's continue our discussion there!
