### ISSUE TITLE
Concurrent use of FieldName appears to deadlock on cache map.

### ISSUE THREAD

**Issue by InvisibleTech** [jpmml/jpmml-model#3]
We use Apache Spark to run our processing concurrently.  Part of this processing uses JPMML FieldName in the process.  The concurrent access of the WeakHashMap cache can produce deadlocks as demonstrated by the stack traces in this gist: https://gist.github.com/InvisibleTech/4e9997d4954ed60382ea

We have a test that reproduces the issue in an extreme way .  We will be posting this as a gist and will link it here.  In the short term we are trying to work around this issue.

Here is a self-contained test that shows the issue using Java and pmml_model:  https://github.com/tdbaldwin/BreakWeakHashMap

NOTE: due to some of the random aspects of this test (like System.gc) we have found that running this test on CENTOS and OSX you may need to run this test more than once to produce the deadlock:

 mvn test

is sufficient.
 
Prior to posting this defect we read these resources:
https://access.redhat.com/solutions/55161  <-- others encountered issues in other stacks
https://github.com/jpmml/jpmml-model/issues/1 <-- we read this and we do not have this issue of use
http://www.adam-bien.com/roller/abien/entry/endless_loops_in_unsychronized_weakhashmap <-- this type of claim is easy to find by searching.
http://mailinator.blogspot.com/2009/06/beautiful-race-condition.html <- interesting discussion

**Comment by vruusmann** [comment]
What is your Java version?

Any suggestions about how to fix it? The obvious solution would be to synchronize the access to the WeakHashMap instance.

Will do performance testing with respect to unsynchronized vs. synchronized access using large PMML files (>5 GB). If the synchronization does not degrade unmarshalling performance too much (say, more than 10%), will do it.

**Comment by InvisibleTech** [comment]
In general, Java 1.8.   We have been talking about not object pooling, as in not caching at all.

**Comment by InvisibleTech** [comment]
In fact we have these set of changes we are testing: https://github.com/warabak/jpmml-model/tree/updating-fieldname-cache-to-use-concurrent-hashmap

**Comment by vruusmann** [comment]
Looks like class `WeakHashMap` is ill-suited for caching purposes anyway. Will think harder about this issue over the weekend and release a fixed version early next week.
