### ISSUE TITLE
Cannot load JSON neither YAML in Android

### ISSUE THREAD

**Issue by brunofmf** [jpmml/jpmml-model#30]
Hi.

I've been trying (a lot) to use jpmml to load PMML-based models to Android apps - the goal, of course, is to have on-device inference - but I've been facing too many problems with too many approaches.

The one I'm reporting here is for both **JSON** and **YAML models**.
Let's take, as example, the decision tree pmml model over the iris dataset that you made available on the archived jpmml-android repository (but you can use any other). I've been using version 1.5.15 of both _jpmml-model_ and _jpmml-evaluator_.

1. The first step was to translate the pmml model to json/yaml (successfully) as follows:
`java -cp pmml-model-example/target/pmml-model-example-executable-1.6-SNAPSHOT.jar org.jpmml.model.example.TranslationExample --input result/model.pmml --output result/model.json`
or
`java -cp pmml-model-example/target/pmml-model-example-executable-1.6-SNAPSHOT.jar org.jpmml.model.example.TranslationExample --input result/model.pmml --output result/model.yaml`

2. Then, placed both files on the assets folder of the Android app (successfully);

3. For model.json file: after loading it from the assets manager, I've used the `JacksonUtil.readPMML(inputStream)` method from the _pmml-model/pmml-model-jackson_ lib. I had no luck and got a huge stack trace;

4. For model.yaml file: I had a little more work but faced a similar problem. I had to import the _com.fasterxml.jackson.dataformat.yaml_ package to set the _YAMLFactory_, which I set on the _objectMapper_. Again, a huge stack trace, pretty similar to the one of the json file.

Both log files are attached to this issue but what you will see is a lot ot "_Unable to resolve java.lang.Class<org.dmg.pmml.XXXX> annotation class YYYY_" and a "_java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/xml/bind/annotation/adapters/XmlAdapter_" which leads to "_Failed resolution of: Lorg/dmg/pmml/adapters/NumberAdapter_".
[Android_json_log.txt](https://github.com/jpmml/jpmml-model/files/6672927/Android_json_log.txt)
[Android_yaml_log.txt](https://github.com/jpmml/jpmml-model/files/6672929/Android_yaml_log.txt)

Any idea why this is happening and how can we, indeed, use json/yaml pmml-based files in Android since, as per the README, it is one of the supported platforms?
A clear tutorial would be nice though.

Cheers,
Bruno

**Comment by vruusmann** [comment]
The `pmml-model-jackson` module is intended for Java SE/EE platforms, as they assume the availability of JAXB runtime.

If you want to use this module on Android platform, then you'd probably need to include some 3rd party helper libraries to compensate for the missing JAXB runtime.

IIRC, you can use Jackson in several modes - following JAXB annotations, following JSON annotations, or a mix of both (JSON overriding JAXB, etc). I can't remember which one is the default mode.

First make sure which annotations are recognied by your Jackson runtime.

> you will see is a lot ot "Unable to resolve java.lang.Class<org.dmg.pmml.XXXX> annotation class YYYY" and a "java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/xml/bind/annotation/adapters/XmlAdapter" which leads to "Failed resolution of: Lorg/dmg/pmml/adapters/NumberAdapter".

There are `@XmlJavaTypeAdapter` annotations in the generated JPMML-Model classes, which reference appropriate XML-to-Java type adapters.

Try including a 3rd party library into your Android project that would provide this interface. For example, `jakarta.xml.bind:jakarta.xml.bind-api(:2.3.3)`. What then?

 > how can we, indeed, use json/yaml pmml-based files in Android since, as per the README, it is one of the supported platforms?

It is supported in a sense that all JPMML-Model library core classes/interfaces only use Android-compatible Java APIs.

See here:
https://github.com/jpmml/jpmml-model/blob/1.5.15/pom.xml#L254-L278

> A clear tutorial would be nice though.

It's been on my TODO list for several years now.

**Comment by vruusmann** [comment]
Other things you may try if the JSON/YAML pathway is blocked:

- Use plain old Java serialization.
- Use Kryo serialization, as implemented by the `org.jpmml:pmml-model-kryo` module.

Using binary serialization you can "transfer" both `org.dmg.pmml.PMML` objects, or fully-initialized `org.jpmml.evaluator.Evaluator` objects. With JSON/YAML you're limited to the former.

**Comment by brunofmf** [comment]
Villu,

I don't know if you want to discuss it here (or in a different issue) but I also add problems with the _jpmml-transpiler_ v1.1.10.

`java -jar target/jpmml-transpiler-executable-1.1-SNAPSHOT.jar --pmml-input result/model.pmml --jar-output result/model.pmml.jar --class-name com.model.DecisionTreeB`

Not to load the jar at runtime and mess with Android's DVM, I've declared the jar as a dependency in my project and, when trying to instantiate the corresponding class, I get this stack trace (using _jpmml-evaluator_ v1.5.15):

`E/AndroidRuntime: FATAL EXCEPTION: main
  java.lang.NoClassDefFoundError: Failed resolution of: Lorg/jpmml/evaluator/ResourceUtil;
    at com.model.DecisionTreeB.<clinit>(DecisionTreeB.java:38)
    at com...model.PmmlEvaluator.load_evaluator(PmmlEvaluator.kt:14)
    at com...MainActivity.onCreate(MainActivity.kt:44)
    at android.app.Activity.performCreate(Activity.java:7136)`

Any on this? Do we need the _pmml-evaluator-extension_? 
Because if we do, we see again a "_Failed resolution of: Lorg/dmg/pmml/adapters/NumberAdapter_".

About plain old Java serialization, well, I had problems there too (even though I was able to workaround them with the archieved _jpmml-android_). I guess I will open a new issue for that.

Thanks.

**Comment by vruusmann** [comment]
> E/AndroidRuntime: FATAL EXCEPTION: main
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/jpmml/evaluator/ResourceUtil;
> Do we need the pmml-evaluator-extension?

Yes, your Android application would need to include both `org.jpmml:pmml-evaluator` and `org.jpmml:pmml-evaluator-extension` modules. The `ResourceUtil` utility class resides in the latter module.

> Because if we do, we see again a "Failed resolution of: Lorg/dmg/pmml/adapters/NumberAdapter".

The `org.jpmml:pmml-evaluator` module should automatically include the `org.jpmml:pmml-model` module, which contains all JAXB type adapter classes. Perhaps it cannot be loaded because of the missing `@XmlJavaTypeAdapter` annotation class again? If so, then you'd need to include JAXB API classes explicitly.

**Comment by brunofmf** [comment]
Ok, it seems that everything is leading towards the same issue...
Loading the JAXB lib is likely to fix the issue (but will come with a cost in the app's size).
For me, you can close this issue!

Thanks.

**Comment by vruusmann** [comment]
> Loading the JAXB lib is likely to fix the issue (but will come with a cost in the app's size).

The `jakarta.xml.bind:jakarta.xml.bind-api(:2.3.3)` library JAR file weighs around 100 kB (0.1 MB). I don't see how that could be a deal-breaker.

**Comment by brunofmf** [comment]
The ` jakarta.xml.bind:jakarta.xml.bind-api(:2.3.3)` isn't enough. The _Xerces2 J_ is also required (another 1.3 MB). That, together with the 600kb of the `org.jpmml:pmml-evaluator` lib and a few more kb of the jar model...

Nonetheless, with the following libs one is able to run transpiled PMML objects in Android successfully (it is also likely to solve JSON/YAML problems - didn't try it though):
`jakarta.xml.bind:jakarta.xml.bind-api:2.3.3`
`xerces:xercesImpl:2.12.1`
`org.jpmml:pmml-evaluator:1.5.15`
`org.jpmml:pmml-evaluator-extension:1.5.15`

**Comment by vruusmann** [comment]
> The jakarta.xml.bind:jakarta.xml.bind-api(:2.3.3) isn't enough. The Xerces2 J is also required (another 1.3 MB).

I'm not aware of any source code-level functionality that would require Xerces2J.

Can you elaborate, what's the exception if Xerces2J is not available? Is there some specific class missing again (some SAX class/interface declaration)? If so, then there's probably a smaller replacement library available (something with an `-api` suffix).

**Comment by brunofmf** [comment]
`java.lang.Error: javax.xml.datatype.DatatypeConfigurationException: Provider org.apache.xerces.jaxp.datatype.DatatypeFactoryImpl not found`
`at javax.xml.bind.DatatypeConverterImpl.<clinit>(DatatypeConverterImpl.java:877)`
`at javax.xml.bind.DatatypeConverter.initConverter(DatatypeConverter.java:125)`

`Caused by: javax.xml.datatype.DatatypeConfigurationException: Provider org.apache.xerces.jaxp.datatype.DatatypeFactoryImpl not found`
`at javax.xml.datatype.DatatypeFactory.newInstance(DatatypeFactory.java:106)`
`... 52 more`

It seems to be Android-related ([https://developer.android.com/reference/kotlin/javax/xml/datatype/DatatypeFactory](url)).

**Comment by vruusmann** [comment]
> java.lang.Error: javax.xml.datatype.DatatypeConfigurationException: Provider org.apache.xerces.jaxp.datatype.DatatypeFactoryImpl not found

See the Javadoc description of [DatatypeFactory](https://docs.oracle.com/en/java/javase/11/docs/api/java.xml/javax/xml/datatype/DatatypeFactory.html).

The Xerces2J is the default implementation, which is used if any other implementation is not configured/made available. It should be possible to implement a dummy `DatatypeFactory` subclass (eg. all methods throw `UnsupportedOperationException`), and instruct the Android application to use it instead.

The idea is that a transpiled `org.dmg.pmml.PMML` object should not need any Java XML APIs to function (you'd only need some interfaces/annotations as exemplified with the `jakarta.xml.bind:jakarta.xml.bind-api` module, but not the actual implementation classes).

Also, it whould be safe to catch and swallow `javax.xml.datatype.DatatypeConfigurationException`. The JPMML part of the codebase should work fine even after that.
