### ISSUE TITLE
License issue with SecondsSinceMidnight.java

### ISSUE THREAD

**Issue by NielsDoucet** [jpmml/jpmml-model#37]
This project specifies the BSD 3 license, but the [SecondsSinceMidnight](https://github.com/jpmml/jpmml-model/blob/master/pmml-model/src/main/java/org/jpmml/model/temporals/SecondsSinceMidnight.java) file has a header with an AGPL license.

Can it be clarified which license applies to this file?

**Comment by vruusmann** [comment]
> This project specifies the BSD 3 license, but the `SecondsSinceMidnight` file has a header with an AGPL license.

Java classes for temporal data types were imported from the JPMML-Evaluator project not long time ago. Looks like I forgot to update all file headers.

> Can it be clarified which license applies to this file?

The JPMML-Model project in its entirety is intended to be compatible with BSD 3-Clause License, as advertised in the `/LICENSE.txt` file.

I will scan the project for potential "JPMML-Evaluator" references, and update file headers accordingly.

Will be corrected in the JPMML-Model version 1.6.4 already.

**Comment by NielsDoucet** [comment]
Thanks for the very fast resolution, much appreciated! ❤️
