### ISSUE TITLE
Supporting PMML model types 

### ISSUE THREAD

**Issue by Tulasamma** [jpmml/jpmml-model#4]
Hi,

What are the pmml model types supports this jpmml model API? I am new to this pmml parsing using jpmml api, can have any reference for execution of pmml models. Please help on this.

**Comment by vruusmann** [comment]
The JPMML-Model library can be used to "parse" and "format" any PMML document that conforms to PMML schema versions 3.0 through 4.2. In other words, all model types are supported.

The JPMML-Evaluator library can "execute" most popular model types. Please see the [features.md] (https://github.com/jpmml/jpmml-evaluator/blob/master/features.md) document for more details.

In both cases, please see the respective README.md files for up-to-date code examples.

Closing this issue as off-topic. You are kindly advised to post such very generic questions to the [JPMML mailing list] (https://groups.google.com/forum/#!forum/jpmml) instead.

**Comment by Tulasamma** [comment]
Need clarification on below models

Baseline model.
Sequence rules.
Text model.
Time series model.

Above models are supporting  or not in jpmml-model API ?

**Comment by vruusmann** [comment]
These four model types can be "parsed" and "formatted" using JPMML-Model library, but they cannot be "executed" using the JPMML-Evaluator library.

If you need to execute those four model types, then you must implement their execution logic yourself.

**Comment by Tulasamma** [comment]
Thanks for the reply.
Can you share any reference url with example for jpmml model to parse and format those models.

**Comment by vruusmann** [comment]
> And more clarification required whether JPMML-Model is open source or not.

Is this a joke or something? We're having this conversation in JPMML-Model issue tracker, right next to its source code tree.
